# Generated by Django 4.1.5 on 2026-02-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='고객명')),
                ('phone', models.CharField(max_length=20, verbose_name='연락처')),
                ('address', models.CharField(help_text='예: 서울시 강남구, 경기도 수원시', max_length=200, verbose_name='설치 지역')),
                ('product_interest', models.CharField(blank=True, max_length=50, null=True, verbose_name='관심 제품군')),
                ('message', models.TextField(blank=True, null=True, verbose_name='상담 내용')),
                ('status', models.CharField(choices=[('new', '신규 문의'), ('contacted', '연락 완료'), ('closed', '종료')], default='new', max_length=20, verbose_name='응대 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='문의 접수일')),
            ],
            options={
                'verbose_name': '설치 상담 문의 (리드)',
                'verbose_name_plural': '설치 상담 리스트',
                'ordering': ['-created_at'],
            },
        ),
    ]
